filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            general:
                linefeed_character: newline
        braces:
            classes_functions:
                class: undefined
                function: undefined
                closure: undefined
            if:
                opening: undefined
            for:
                opening: undefined
            while:
                opening: undefined
            do_while:
                opening: undefined
            switch:
                opening: undefined
            try:
                opening: undefined
        upper_lower_casing:
            keywords:
                general: undefined
            constants:
                true_false_null: undefined
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.tmp'
                coverage:
                    file: 'coverage.tmp'
                    format: 'php-clover'
